### ISSUE TITLE
TF State

### ISSUE THREAD

**Issue by tomdavidson** [martezr/stackstorm-terraform#3]
How is the terrafrom state handled ?

**Comment by martezr** [comment]
@tomdavidson The Terraform state is handled the same way it would be on any other machine. Remote state should be used to ensure the state is not lost.

**Comment by tomdavidson** [comment]
@martezr thank you for replying so quickly.

Right, but configuring that remote state is out of plan - example of a workflow configuring the remote state and then applying the plan? This could just be my StackStorm inexperience talking.

**Comment by martezr** [comment]
@tomdavidson You can stitch a back end initialization together with a subsequent plan and finally an apply. This can be done by creating a workflow that includes all three actions tied together.

**Comment by tomdavidson** [comment]
thank you for the contrib and for the help
